<table cellpadding="5" cellspacing="0" width="200" align="right" border="2">
<tr>
	<td class="error" style="font-weight:normal;font-size:10px">
	ClickBank recently changed the structure of their XML datafeed. They did this without notice of any kind, and without changing the version number of the feed. This led to problems with the product information and our datafeed files over the last few days. We have now updated our code to work with the new structure. We apologize for any inconvenience this may have caused our users.
	</td>
</tr>
</table>