<table cellpadding="6" cellspacing="0" border="0" width="100%" style="font-weight:bold;font-size:10px">
<tr>
	<td align="right">
	<a href="clickbank_stats.php">STATS HOME</a>&nbsp;&nbsp;&nbsp;
	<a href="clickbank_stats_gainers.php">BIG MOVERS</a>&nbsp;&nbsp;&nbsp;
	<a href="clickbank_stats_losers.php">BIG LOSERS</a>&nbsp;&nbsp;&nbsp;
	<a href="clickbank_stats_gravity.php">GRAVITY-REFERRED PERCENTAGE</a>&nbsp;&nbsp;&nbsp;
	<a href="clickbank_new_products.php">NEW PRODUCTS</a>&nbsp;&nbsp;&nbsp;
	<a href="clickbank_dropped_products.php">DROPPED PRODUCTS</a>&nbsp;&nbsp;&nbsp;
	</td>
</tr>
</table>
<br />
	